### ISSUE TITLE
开启 CONFIG_USBDEV_ADVANCE_DESC 后无法枚举

### ISSUE THREAD

**Issue by RikkaW** [sakumisu/CherryUSB#112]
CherryUSB 版本：v0.9.0 (9d24ae4)
MCU：CH32V307

虽然不知道为什么但是把 usbd_get_descriptor 里面所有这种的都改成 `memcpy(*data, xxx_descriptor, *len)` 这样的就又正常工作了（

https://github.com/sakumisu/CherryUSB/blob/85a494326a45550e27fadd6aced0691e38aa4aba/core/usbd_core.c#L173-L176

**Comment by sakumisu** [comment]
描述符都是放在flash，ch32 dma无法访问flash，所以需要memcpy，所以不要使用高级功能，没有做memcpy处理

**Comment by tpunix** [comment]
描述符不声明为const，就会放在sram里面了。
