### ISSUE TITLE
移植请教

### ISSUE THREAD

**Issue by ThinkCodeStudio** [sakumisu/CherryUSB#113]
我想移植到 AT32F435 这款单片机上, 这款单片机也是用的dwc2 IP核, 理论上我是不用修改寄存器地址的, 但是有很多函数我需要替换成AT32的函数.
 我要在什么位置初始化时钟和IO, port文件中的USB中断里做了什么, 我要怎么修改它, 使协议栈能工作

**Comment by sakumisu** [comment]
参考，https://gitee.com/jonaswen/hmi-board-daplink/tree/master/libraries

**Comment by sakumisu** [comment]
USB 中断做了什么，不需要关心
