### ISSUE TITLE
Can you please point me to a BL702 Host example [HID]?

### ISSUE THREAD

**Issue by rog77** [sakumisu/CherryUSB#14]
HI,

I'm interested in using this library in order to utilise a USB keyboard with a BL702 acting as the host, with a view to outputting keystrokes over uart as ascii - is there an example of such functionality that already exists that you might please point me to? Thanks!

**Comment by sakumisu** [comment]
Hello，BL702 does not support host, the coming chips will support.Thank you!You can use other chips that i have supported.

**Comment by rog77** [comment]
Thank you for your response, it looks like I must have misread/misinterpretated the data sheet for that chip; which is a shame as I needed to use that particular chip, as that is the one on the board I wish to adapt... Ah well.
