### ISSUE TITLE
按照26视频重复你的步骤，打开uVision没有usb_stack文件夹及下面的3个文件

### ISSUE THREAD

**Issue by kylongmu** [sakumisu/CherryUSB#23]
选择与你一样的工程rt-thread\bsp\stm32\stm32f103-atk-nano
uVision 5.36
RT-Thread v4.1.0
CubeMX 6.5

**Comment by sakumisu** [comment]
视频早过时了，参考read me底下文档来

**Comment by kylongmu** [comment]
参考readme做了，也编译成功，就是没有cdc设备，感觉步骤好多，重复了2遍都失败，看来是我水平low了，从入门到放弃。

**Comment by sakumisu** [comment]
不就写一个 usb_dc_low_level_init，哪里步骤多了，移植也算步骤的话当我没说

**Comment by sakumisu** [comment]
有问题可以qq群：642693751
