### ISSUE TITLE
Sconscripts的更改和rtthread软件包中Kconfig生成的配置宏不匹配

### ISSUE THREAD

**Issue by blta** [sakumisu/CherryUSB#26]
最近对Sconscripts的更改和软件包在rtthread软件包中Kconfig生成的配置宏不匹配，导致source和 include不能正确配置
需要更新一下软件包的Kconfig 或者 恢复之前的Sconscripts
虽然现在改的简洁些，但是感觉不太符合rtthread软件包的宏格式

**Comment by sakumisu** [comment]
更新软件包的Kconfig，这个本身就是需要更新的啊，不存在一直不更新的情况

**Comment by blta** [comment]
跟新延时问题，已同步，ok
