### ISSUE TITLE
Porting copyright issue

### ISSUE THREAD

**Issue by Devilliv** [sakumisu/CherryUSB#27]
@sakumisu 您好，
如果移植CherryUSB到一个SDK中，请问作者对license和copyright有什么要求吗？我看readme也没有特别提及。

望回复，谢谢！

**Comment by sakumisu** [comment]
走 apache licence 2.0 的要求就可以了，意味着保留原作者署名、license等

**Comment by Devilliv** [comment]
好的，谢谢！
