### ISSUE TITLE
stm32f0系列单片机枚举失败

### ISSUE THREAD

**Issue by yongfeicao** [sakumisu/CherryUSB#43]
尝试在stm32f072上测试，发现以下问题：
需要实现int usb_dc_attach(void);
同时在头文件中追加相关函数。
在做了上面的修改之后电脑可以发现usb设备，
但是枚举失败，提示获取不了设备描述符

**Comment by sakumisu** [comment]
加群讨论吧

**Comment by yongfeicao** [comment]
只需要将代码中的宏定义修改就可以：
宏定义PMA_ACCESS 的值从 2修改为1
