### ISSUE TITLE
[E/USB] ep:86 clear halt

### ISSUE THREAD

**Issue by SmartElec** [sakumisu/CherryUSB#45]
stm32f103c8t6
demo\cdc_acm_hid_msc_template.c
need modify usb_dc_fsdev.c USB_RAM_SIZE to 1024
```
#ifndef USB_RAM_SIZE
#define USB_RAM_SIZE 512
#endif
```

and hid endpoint get errors
USB_REQUEST_CLEAR_FEATURE:
 [E/USB] ep:86 clear halt

导致hid设备出现感叹号，这个应该如何解决

**Comment by sakumisu** [comment]
谁让你改成1024的？这是硬件规定的，怎么能随便改？

**Comment by sakumisu** [comment]
fsdev不支持这个demo

**Comment by SmartElec** [comment]
> 谁让你改成1024的？这是硬件规定的，怎么能随便改？
```
[E/USB] Ep pma 134 overflow
[E/USB] standard request error
```

**Comment by sakumisu** [comment]
超了就是超了，没办法，要么换芯片

**Comment by SmartElec** [comment]
> 

OK，那F103C8T6就没法实现daplink v2.0的全部功能了。HID + CDC + MSC拖拽

**Comment by sakumisu** [comment]
是这样的，我已经在准备做一个 daplink全芯片版本的工程，支持所有芯片平台
