### ISSUE TITLE
Very minor typo in directory name

### ISSUE THREAD

**Issue by robertlipe** [sakumisu/CherryUSB#47]
I don't know how to create a PR for this.

In https://github.com/sakumisu/CherryUSB/tree/master/docs the first directory should probably be "assets" (resources belonging to a project" and not "asserts" (like a programmer checking that something is true).

Looks like a cool project! Congrats on creating it.

**Comment by sakumisu** [comment]
Thank you, this is a spelling error.

**Comment by sakumisu** [comment]
done
