### ISSUE TITLE
GD32 dwc2驱动的GCCFG_NOVBUSSENS寄存器兼容性和stm32存在区别

### ISSUE THREAD

**Issue by yyjdelete** [sakumisu/CherryUSB#64]
虽然dwc2的文档里面写的支持GD32F30X_CL,  但在GD32305R-START(GD32F30X_CL)的开发板上测试的时候连电脑识别失败

和gd32的官方的代码对比了下, 发现不开CONFIG_DWC2_VBUS_SENSING_ENABLE的时候, gd32即使设置了USB_OTG_GCCFG_NOVBUSSENS, 也必须设置USB_OTG_GCCFG_VBUSASEN/_VBUSBSEN才能正常工作(gd32官方驱动这里就和stm32的有区别, gd32官方设置的是两个都设置了, 实测设置至少其一就能工作, 不知道a和b啥区别, stm32是两个都取消了)
(另参考http://www.elmagnifico.tech/2021/06/21/CUBEMX-GD32F450-USB/#usbfs_gccfg)

https://github.com/sakumisu/CherryUSB/blob/f1a5345f26c645e2e1d30dbccb0eee19490e0619/port/dwc2/usb_dc_dwc2.c#L574-L580
虽然没用但怀疑usb_hc_dwc2也是一样的
这里希望能加个宏定义或者在[USB IP 勘误文档](https://cherryusb.readthedocs.io/zh_CN/latest/porting_usbip.html)中给个说明
```c
    #ifdef CONFIG_DWC2_GD32
    USB_OTG_GLB->GCCFG |= USB_OTG_GCCFG_VBUSASEN | USB_OTG_GCCFG_VBUSBSEN;
    #else
    USB_OTG_GLB->GCCFG &= ~USB_OTG_GCCFG_VBUSBSEN;
    USB_OTG_GLB->GCCFG &= ~USB_OTG_GCCFG_VBUSASEN;
    #endif
```

**Comment by sakumisu** [comment]
感谢指正。这个我觉得是 GD 自己买 ip以后，硬件没做好，弄的一个软件 workaround方式，这个兼容的话确实没办法预料

**Comment by sakumisu** [comment]
感谢指正。这个我觉得是 GD 自己买 ip以后，硬件没做好，弄的一个软件 workaround方式，这个兼容的话确实没办法预料

**Comment by sakumisu** [comment]
感谢指正。这个我觉得是 GD 自己买 ip以后，硬件没做好，弄的一个软件 workaround方式，这个兼容的话确实没办法预料

**Comment by wuwbobo2021** [comment]
目前 CherryUSB 已经不支持 GD32： “由于无法读取 DWC2 配置信息，并且有部分寄存器是非标准的，因此暂时无法支持 GD 系列”。`usb_glue_gd.c` 中缺少新的 `dwc2_get_user_params` 函数的实现，自己手动实现该函数后测试固件仍然无法处理USB枚举，不知道还需要改动哪些地方。将 CherryUSB 换成 <https://github.com/CherryUSB/cherryusb_gd32> 中的版本后很快调通 CDC-ACM 示例（GD32F470）。

这是我第一次尝试使用 CherryUSB，原因是官方 USB 固件库的批量传输例程及其调用的 CDC-ACM 设备类 API 令人困惑，似乎除了回环传输什么也做不了，除非修改设备类 API。

不知何故，<https://github.com/CherryUSB/cherryusb_gd32> 已于今年7月7日被 @sakumisu 封存，暂未找到其他支持 GD32 的第三方 USB 固件库。

**Comment by sakumisu** [comment]
> 目前 CherryUSB 已经不支持 GD32： “由于无法读取 DWC2 配置信息，并且有部分寄存器是非标准的，因此暂时无法支持 GD 系列”。`usb_glue_gd.c` 中缺少新的 `dwc2_get_user_params` 函数的实现，自己手动实现该函数后测试固件仍然无法处理USB枚举，不知道还需要改动哪些地方。将 CherryUSB 换成 https://github.com/CherryUSB/cherryusb_gd32 中的版本后很快调通 CDC-ACM 示例（GD32F470）。
> 
> 这是我第一次尝试使用 CherryUSB，原因是官方 USB 固件库的批量传输例程及其调用的 CDC-ACM 设备类 API 令人困惑，似乎除了回环传输什么也做不了，除非修改设备类 API。
> 
> 不知何故，https://github.com/CherryUSB/cherryusb_gd32 已于今年7月7日被 [@sakumisu](https://github.com/sakumisu) 封存，暂未找到其他支持 GD32 的第三方 USB 固件库。

如文档所言，放弃移植。
