### ISSUE TITLE
usbhub拔出的时候插在hub上的设备不会调用 usbh_device_unmount_done_callback 通知

### ISSUE THREAD

**Issue by supf1994** [sakumisu/CherryUSB#65]
将hid插在hub上面，直接拔出hid设备时可以收到usbh_device_unmount_done_callback 回调通知，如果不拔出将hub直接拔出只会收到hub的usbh_device_unmount_done_callback 回调，而上面的hid 无回调

**Comment by sakumisu** [comment]
现在的代码是这样的，只对插拔的设备启效果。后续会改成 class 的

**Comment by sakumisu** [comment]
已经更新
