### ISSUE TITLE
usb hub 多次枚举导致 No memory to alloc hub class

### ISSUE THREAD

**Issue by supf1994** [sakumisu/CherryUSB#66]
测试STM32F407的USB主机模式的时候使用USB延长线连接hub，导致usb线非常的长，如果先将hid接入到hub再接入控制器中，不会有问题；如果先将hub接入控制器，再将hid接入hub，则会出现  
![image](https://user-images.githubusercontent.com/23397492/203294147-d0ffd56e-8d06-4d7b-89ec-89e57d0b55a4.png)
跟踪调试之后发现，在后一种情况下，hid接入hub时，再中断函数中检查  USB_OTG_HPRT 寄存器值为 0x00021008，之后唤醒 usb-hub线程进行事件处理，在 usb-hub 线程中再次读取 USB_OTG_HPRT 寄存器值为  0x00021401，状态再次变成上电，导致hub设备在没有调用  CLASS_DISCONNECT 的情况下再次调用 CLASS_CONNECT，引发  No memory to alloc hub class 错误，并且再次拔插USB也无法恢复，必须重启stm32

**Comment by sakumisue** [comment]
stm32 的话推荐就别用 hub了，尤其是带 hid的设备，一部分还跟供电电路有关，hub需要自供电，不可使用单片机供电

**Comment by supf1994** [comment]
上线的项目是接多个HID的场景，必须得有HUB，目前正常供电是没问题的，就是接延长线的时候会出现这种情况，我这边修改了 static void usbh_hub_events(struct usbh_hub *hub) 函数解决了该问题，修改后的代码如下：
`static void usbh_hub_events(struct usbh_hub *hub)
{
    struct usbh_hubport *child;
    struct hub_port_status port_status;
    uint8_t portchange_index;
    uint16_t portstatus;
    uint16_t portchange;
    uint16_t mask;
    uint16_t feat;
    uint8_t speed;
    int ret;

    if (!hub->connected) {
        return;
    }

    for (uint8_t port = 0; port < hub->hub_desc.bNbrPorts; port++) {
        portchange_index = hub->int_buffer[0];

        USB_LOG_DBG("Port change:0x%02x\r\n", portchange_index);

        if (!(portchange_index & (1 << (port + 1)))) {
            continue;
        }
        portchange_index &= ~(1 << (port + 1));
        USB_LOG_DBG("Port %d change\r\n", port + 1);

        /* Read hub port status */
        ret = usbh_hub_get_portstatus(hub, port + 1, &port_status);
        if (ret < 0) {
            USB_LOG_ERR("Failed to read port %u status, errorcode: %d\r\n", port + 1, ret);
            continue;
        }

        portstatus = port_status.wPortStatus;
        portchange = port_status.wPortChange;

        USB_LOG_DBG("port %u, status:0x%02x, change:0x%02x\r\n", port + 1, portstatus, portchange);

        /* First, clear all change bits */
        mask = 1;
        feat = HUB_PORT_FEATURE_C_CONNECTION;
        while (portchange) {
            if (portchange & mask) {
                ret = usbh_hub_clear_feature(hub, port + 1, feat);
                if (ret < 0) {
                    USB_LOG_ERR("Failed to clear port %u, change mask:%04x, errorcode:%d\r\n", port + 1, mask, ret);
                    continue;
                }
                portchange &= (~mask);
            }
            mask <<= 1;
            feat++;
        }

        portchange = port_status.wPortChange;

        /* Second, if port changes, debounces first */
        if (portchange & HUB_PORT_STATUS_C_CONNECTION) {
            uint16_t connection = 0;
            uint16_t debouncestable = 0;
            for (uint32_t debouncetime = 0; debouncetime < DEBOUNCE_TIMEOUT; debouncetime += DEBOUNCE_TIME_STEP) {
                usb_osal_msleep(DEBOUNCE_TIME_STEP);
                /* Read hub port status */
                ret = usbh_hub_get_portstatus(hub, port + 1, &port_status);
                if (ret < 0) {
                    USB_LOG_ERR("Failed to read port %u status, errorcode: %d\r\n", port + 1, ret);
                    continue;
                }

                portstatus = port_status.wPortStatus;
                portchange = port_status.wPortChange;

                USB_LOG_DBG("Port %u, status:0x%02x, change:0x%02x\r\n", port + 1, portstatus, portchange);
                if ((portstatus & HUB_PORT_STATUS_CONNECTION) == connection) {
                    if (connection) {
                        if (++debouncestable == 4) {
                            break;
                        }
                    }
                } else {
                    debouncestable = 0;
                }

                connection = portstatus & HUB_PORT_STATUS_CONNECTION;

                if (portchange & HUB_PORT_STATUS_C_CONNECTION) {
                    usbh_hub_clear_feature(hub, port + 1, HUB_PORT_FEATURE_C_CONNECTION);
                }
            }

            /* Last, check connect status */
            if (portstatus & HUB_PORT_STATUS_CONNECTION) {
                ret = usbh_hub_set_feature(hub, port + 1, HUB_PORT_FEATURE_RESET);
                if (ret < 0) {
                    USB_LOG_ERR("Failed to reset port %u,errorcode:%d\r\n", port, ret);
                    continue;
                }

                usb_osal_msleep(DELAY_TIME_AFTER_RESET);
                /* Read hub port status */
                ret = usbh_hub_get_portstatus(hub, port + 1, &port_status);
                if (ret < 0) {
                    USB_LOG_ERR("Failed to read port %u status, errorcode: %d\r\n", port + 1, ret);
                    continue;
                }

                portstatus = port_status.wPortStatus;
                portchange = port_status.wPortChange;
                if (!(portstatus & HUB_PORT_STATUS_RESET) && (portstatus & HUB_PORT_STATUS_ENABLE)) {
                    if (portchange & HUB_PORT_STATUS_C_RESET) {
                        ret = usbh_hub_clear_feature(hub, port + 1, HUB_PORT_FEATURE_C_RESET);
                        if (ret < 0) {
                            USB_LOG_ERR("Failed to clear port %u reset change, errorcode: %d\r\n", port, ret);
                        }
                    }

                    if (portstatus & HUB_PORT_STATUS_HIGH_SPEED) {
                        speed = USB_SPEED_HIGH;
                    } else if (portstatus & HUB_PORT_STATUS_LOW_SPEED) {
                        speed = USB_SPEED_LOW;
                    } else {
                        speed = USB_SPEED_FULL;
                    }

                    child = &hub->child[port];
                    if(child->connected)    //之前的状态还连接着，先卸载断开
                    {
                        USB_LOG_WRN("New device on Hub %u, Port %u is connected\r\n", hub->index, port + 1);
                        child->connected = false;
                        usbh_hport_deactivate_ep0(child);
                        for (uint8_t i = 0; i < child->config.config_desc.bNumInterfaces; i++) {
                            if (child->config.intf[i].class_driver && child->config.intf[i].class_driver->disconnect) {
                                CLASS_DISCONNECT(child, i);
                            }
                        }

                        USB_LOG_INFO("Device on Hub %u, Port %u disconnected\r\n", hub->index, port + 1);
                        usbh_device_unmount_done_callback(child);
                        child->config.config_desc.bNumInterfaces = 0;
                    }

                    memset(child, 0, sizeof(struct usbh_hubport));
                    child->parent = hub;
                    child->connected = true;
                    child->port = port + 1;
                    child->speed = speed;

                    USB_LOG_INFO("New %s device on Hub %u, Port %u connected\r\n", speed_table[speed], hub->index, port + 1);

                    if (usbh_enumerate(child) < 0) {
                        USB_LOG_ERR("Port %u enumerate fail\r\n", port + 1);
                    }
                } else {
                    USB_LOG_ERR("Failed to enable port %u\r\n", port + 1);
                    continue;
                }
            } else {
                child = &hub->child[port];
                child->connected = false;
                usbh_hport_deactivate_ep0(child);
                for (uint8_t i = 0; i < child->config.config_desc.bNumInterfaces; i++) {
                    if (child->config.intf[i].class_driver && child->config.intf[i].class_driver->disconnect) {
                        CLASS_DISCONNECT(child, i);
                    }
                }

                USB_LOG_INFO("Device on Hub %u, Port %u disconnected\r\n", hub->index, port + 1);
                usbh_device_unmount_done_callback(child);
                child->config.config_desc.bNumInterfaces = 0;
            }
        }
    }

    /* Start next hub int transfer */
    if (!hub->is_roothub && hub->connected) {
        usbh_submit_urb(&hub->intin_urb);
    }
}`

在进入枚举之前先判断  child->connected 状态，如果状态为true，执行 CLASS_DISCONNECT 函数，可以解决该问题，但不知道会不会引入其他问题

**Comment by sakumisu** [comment]
hid使用的是 full speed？stm32这边之前测试如果使用低速的，可能会有问题。其次 stm32上用 hub，这个比较少见，可能会存在一些坑，不过我测试正常插 4个 u盘没事，不过最好少用低速的，因为hub对 低速需要使用，split 事务。split 事务这部分寄存器虽然有，但是具体能不能用是不知道的。

**Comment by sakumisu** [comment]
有问题的话可以加下readme底下qq群，谢谢。觉得项目不错的话，给个 star 吧。

**Comment by supf1994** [comment]
> hid使用的是 full speed？stm32这边之前测试如果使用低速的，可能会有问题。其次 stm32上用 hub，这个比较少见，可能会存在一些坑，不过我测试正常插 4个 u盘没事，不过最好少用低速的，因为hub对 低速需要使用，split 事务。split 事务这部分寄存器虽然有，但是具体能不能用是不知道的。

使用的是full speed， 这个问题的应该是因为在短暂的掉电情况下在usb-hub线程中再次读取 USB_OTG_HPRT 值时与中断函数中读到的值已经不相同，使得在没有卸载设备的情况下再次枚举，没有正确的释放之前的资源

**Comment by supf1994** [comment]
> 有问题的话可以加下readme底下qq群，谢谢。觉得项目不错的话，给个 star 吧。

好的

**Comment by supf1994** [comment]
我们目前的使用是在工厂和仓库中，环境比较恶劣，偶尔会出现这种情况，在公司测试的时候使用电磁铁干扰hub和加长USB线的情况下也会出现这种问题

**Comment by sakumisu** [comment]
patch 已经更新到主线
