### ISSUE TITLE
please replace parameter "class" with another name

### ISSUE THREAD

**Issue by QIANWC** [sakumisu/CherryUSB#8]
**class** is a reserved keyword in C++, error occurs when included by any C++ file.
example:
`void usbd_class_register(usbd_class_t *class);`

**Comment by sakumisu** [comment]
Yep,thanks,i will fix this.

**Comment by sakumisu** [comment]
Have done in this commit [9abb92aa](https://github.com/sakumisu/usb_stack/commit/9abb92aad0b2c69e56b73cae5cdd49f4f83df25c)

**Comment by QIANWC** [comment]
some names still need patch:
![image](https://user-images.githubusercontent.com/25631947/151981011-29b545b0-7eb4-4500-a512-912c0147caf8.png)

**Comment by sakumisu** [comment]
Sry,my fault.

**Comment by QIANWC** [comment]
fine

**Comment by sakumisu** [comment]
已修复此问题，关闭issue
