### ISSUE TITLE
STM32f401. Failed to get device descriptor,errorcode:-116

### ISSUE THREAD

**Issue by ND-00** [sakumisu/CherryUSB#83]
I'm trying to make usb host on the stm32f401ccu6. This error occurs when connecting a usb device. I'm using CubeIDE. My code is copied from the stm32f429igt6 example. I followed the steps according to the guide.
That's all I did.

sakumisu, thanks for the great work! I hope the issue can be resolved

**Comment by sakumisu** [comment]
You should check whether it supports dma mode.

**Comment by ND-00** [comment]
MCU supports DMA mode. Or do you mean this?
![image](https://user-images.githubusercontent.com/83452732/212958932-f44e6c68-adaf-43bb-bd9f-76353ebae9ba.png)
My MCU does not have this option. Is it critical?
P.S. Sorry, maybe I'm asking very stupid questions, but I can't solve this problem for a long time. 
Error log
![image](https://user-images.githubusercontent.com/83452732/212959663-49aa3e10-e304-42cb-8cae-cc83545f8c00.png)

**Comment by sakumisu** [comment]
Right, only support dma not fifo mode, and pin must be pb14,  pb15

**Comment by ND-00** [comment]
The USB connector is configured and connected correctly. My pins are pb11, pb12. Do you have any ideas about this issue? I can't find the location of the problem

**Comment by sakumisu** [comment]
sorry, must be another port with pin  PB14  PB15，PA11  do not support because it does not support dma

**Comment by ND-00** [comment]
This MCU has no other outputs. I close the question. Thanks for the help!

**Comment by sakumisu** [comment]
You can use stm32f429 and have a try.
