### ISSUE TITLE
Class 的注册方式能使用数组吗？

### ISSUE THREAD

**Issue by AnemosCiel** [sakumisu/CherryUSB#90]
Class的注册使用编译进内存的方式在不同编译器下移植起来太麻烦了，对编译原理和内存分区理解不够，能有一个分支用数组的方式实现吗？将Class的句柄加进数组就是注册。
我尝试改了一下，但是似乎哪里出了点问题。

**Comment by sakumisu** [comment]
跟编译原理和内存分区没有一点关系，仅仅只是链表跟数组的赋值和查找区别，这可是大学的基本功啊。
