### ISSUE TITLE
USB Host多个HID设备该如何处理？

### ISSUE THREAD

**Issue by arilink** [sakumisu/CherryUSB#97]
查看USB Host的示例代码 看起来每个类型的设备是支持了一个设备  如果想要支持多个相同类型的设备该如何处理呢？ 我看usbx和tinyusb都是自动枚举  然后根据地址回调的

**Comment by sakumisu** [comment]
这还需要我说嘛？自己改name啊

**Comment by sakumisu** [comment]
还要用户自己知道地址，也太low了吧

**Comment by sakumisu** [comment]
要是插了7 8个设备，谁知道是哪个

**Comment by sakumisu** [comment]
dev/input0 , dev/input1 ...

**Comment by arilink** [comment]
相当于我不用管底层  只需要根据我设备的数量创建对应的dev/input0 , dev/input1 ... 和他们的回调函数  有对应的设备数据进来回调函数里处理就ok
